# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mfc < Formula
  desc "Utility toolbelt for Mission Focus engineers"
  homepage "https://missionfocus.com"
  version "2.5.22"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/missionfocus/mfc/releases/download/v2.5.22/mfc_2.5.22_macOS_x86_64.tar.gz"
      sha256 "a5fc1612f1be807fe4c4d8bf585eebb1dcee568de3fdff9fa48ff399b72953db"
    end
    if Hardware::CPU.arm?
      url "https://github.com/missionfocus/mfc/releases/download/v2.5.22/mfc_2.5.22_macOS_arm64.tar.gz"
      sha256 "2b58a5eb0c99a0e47ba68cca5e8ebd6163d520258d5b24dcda252e59076e9b1f"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/missionfocus/mfc/releases/download/v2.5.22/mfc_2.5.22_Linux_x86_64.tar.gz"
      sha256 "9e7123366eb08b99d5b954ea1295e51fad56c0ced18628eac11f91d5f945b250"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/missionfocus/mfc/releases/download/v2.5.22/mfc_2.5.22_Linux_arm64.tar.gz"
      sha256 "daa597f6be444703dad5d611129856ec5b5f7384edd74dec9eab19ce10f2862a"
    end
  end

  def install
    bin.install "mfc"
  end
end
