# This file was generated by GoReleaser. DO NOT EDIT.
cask "crowsnest" do
  version "0.0.2"

  on_macos do
    on_arm do
      sha256 "4b71082e77488d43e59c4c882d11265f8971c23e3af2789f273d3d93975779ed"
      url "https://github.com/missionfocus/homebrew-tap/releases/download/crowsnest-v#{version}/crowsnest_darwin_arm64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "fdfb05104f4e6ebc582aa428cc1d9ac9dc3b54ff58df231ea2de048cc934ff04"
      url "https://github.com/missionfocus/homebrew-tap/releases/download/crowsnest-v#{version}/crowsnest_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "717d494d86e656d43b418f8a598696e337a3adc3a784396f4403fa8b9acb5f16"
      url "https://github.com/missionfocus/homebrew-tap/releases/download/crowsnest-v#{version}/crowsnest_linux_x86_64.tar.gz"
    end
  end

  name "crowsnest"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "crowsnest"

  # No zap stanza required
end
