# This file was generated by GoReleaser. DO NOT EDIT.
cask "crowsnest" do
  version "0.0.3"

  on_macos do
    on_arm do
      sha256 "5b2d5d3c19d644b8275674a99b52fcd3d4862022538baf3daf9ad2d2bf999236"
      url "https://github.com/missionfocus/homebrew-tap/releases/download/crowsnest-v#{version}/crowsnest_darwin_arm64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "21011793677f3e61203063c9f66035988d241a7655dd4e4a19d8ad6c7f10880e"
      url "https://github.com/missionfocus/homebrew-tap/releases/download/crowsnest-v#{version}/crowsnest_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a790c902681766ae749d258626d662c01b0199d05c35c35d8cd8990b97b65f8c"
      url "https://github.com/missionfocus/homebrew-tap/releases/download/crowsnest-v#{version}/crowsnest_linux_x86_64.tar.gz"
    end
  end

  name "crowsnest"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "crowsnest"

  # No zap stanza required
end
