# This file was generated by GoReleaser. DO NOT EDIT.
cask "crowsnest" do
  version "0.0.1"

  on_macos do
    on_arm do
      sha256 "6f221f8a6a0debf92aa029d19e116c7dad4b1ede0ca47bb5fbc2a59ae422e287"
      url "https://github.com/missionfocus/homebrew-tap/releases/download/crowsnest-v#{version}/crowsnest_darwin_arm64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ad0a867d10f53e489e55aa816ad4b61cb51c8b5cf3bf0727ec90a5310a50f2a8"
      url "https://github.com/missionfocus/homebrew-tap/releases/download/crowsnest-v#{version}/crowsnest_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7f0ae0a908a484f7a5f93e6c6bf9c3f38f7d9acefd24041346bf0e8f019cb069"
      url "https://github.com/missionfocus/homebrew-tap/releases/download/crowsnest-v#{version}/crowsnest_linux_x86_64.tar.gz"
    end
  end

  name "crowsnest"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "crowsnest"

  # No zap stanza required
end
