# This file was generated by GoReleaser. DO NOT EDIT.
cask "inkandharpoon" do
  version "0.0.1"

  on_macos do
    on_arm do
      sha256 "b2f92310d86d648bcaea79c06fa41523f97306a3ead1e52aeb3bd9bccf43b6f6"
      url "https://github.com/missionfocus/homebrew-tap/releases/download/inkandharpoon-v#{version}/inkandharpoon_#{version}_darwin_arm64.zip"
    end
  end
  on_linux do
    on_arm do
      sha256 "ecdd9416adbe31d55fff0114416aed6d9f5962c9d92db5488f20992e0bd3fedf"
      url "https://github.com/missionfocus/homebrew-tap/releases/download/inkandharpoon-v#{version}/inkandharpoon_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "361a24e7275a84c5504744ada4c4b2eaecc0fc3e17019c6a7ba011c79a05013a"
      url "https://github.com/missionfocus/homebrew-tap/releases/download/inkandharpoon-v#{version}/inkandharpoon_#{version}_linux_amd64.tar.gz"
    end
  end

  name "inkandharpoon"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "inkandharpoon"

  # No zap stanza required
end
