# This file was generated by GoReleaser. DO NOT EDIT.
cask "videlicet" do
  version "0.0.81"

  on_macos do
    on_arm do
      sha256 "d9997d4e2a61ece6245c79d407fcb84e82a6919e5bc17662f0d895291c47bbbe"
      url "https://github.com/missionfocus/homebrew-tap/releases/download/videlicet-v#{version}/videlicet_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e4fb0a211d43b89008a6eab344a61f4dd356a9b92129e5d6a4d70849ce34545a"
      url "https://github.com/missionfocus/homebrew-tap/releases/download/videlicet-v#{version}/videlicet_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "videlicet"
  desc "Operator CLI for Videlicet -- loads page scans into a running app"
  homepage "https://github.com/missionfocus/edc"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "videlicet"

  # No zap stanza required
end
