# This file was generated by GoReleaser. DO NOT EDIT.
cask "videlicet" do
  version "0.0.7"

  on_macos do
    on_arm do
      sha256 "1ecb1b144de064b96b68c645d249b869960b90bf8c270bec8f9570b08d31acc1"
      url "https://github.com/missionfocus/homebrew-tap/releases/download/videlicet-v#{version}/videlicet_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/missionfocus/homebrew-tap/"
    end
    on_intel do
      sha256 "f657f64bb9d00fe1e365219653855cada4389b613a12546080c63de25ffae8e7"
      url "https://github.com/missionfocus/homebrew-tap/releases/download/videlicet-v#{version}/videlicet_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/missionfocus/homebrew-tap/"
    end
  end

  name "videlicet"
  desc "Operator CLI for Videlicet -- loads page scans into a running app"
  homepage "https://github.com/missionfocus/edc"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "videlicet"

  # No zap stanza required
end
