# This file was generated by GoReleaser. DO NOT EDIT.
cask "videlicet" do
  version "0.0.8"

  on_macos do
    on_arm do
      sha256 "ca5823c80e68c5000020c54991837e8957e94230377c703f65eb1b889a464af7"
      url "https://github.com/missionfocus/homebrew-tap/releases/download/videlicet-v#{version}/videlicet_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "162ac72d05102d784ccced5d4cb139494ebc89e392b2a9ab35c3fd93b55a2fb9"
      url "https://github.com/missionfocus/homebrew-tap/releases/download/videlicet-v#{version}/videlicet_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "videlicet"
  desc "Operator CLI for Videlicet -- loads page scans into a running app"
  homepage "https://github.com/missionfocus/edc"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "videlicet"

  # No zap stanza required
end
