# This file was generated by GoReleaser. DO NOT EDIT.
cask "wharf" do
  version "0.0.1"

  on_macos do
    on_arm do
      sha256 "7c700d0a47ce830221186edcab78bb6ff45cf98af91bf781feff08e3b58e6527"
      url "https://github.com/missionfocus/homebrew-tap/releases/download/wharf-v#{version}/wharf_darwin_arm64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7d9762c8865914c93608f7a45facbff44458638164c0cc8987b93d7a471a4e14"
      url "https://github.com/missionfocus/homebrew-tap/releases/download/wharf-v#{version}/wharf_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "479301899adb610002d0e5af7f2a8c44811480d1f8dfb0bde4d19d18fbcca52b"
      url "https://github.com/missionfocus/homebrew-tap/releases/download/wharf-v#{version}/wharf_linux_x86_64.tar.gz"
    end
  end

  name "wharf"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wharf"

  # No zap stanza required
end
