# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mfc < Formula
  desc "Utility toolbelt for Mission Focus engineers"
  homepage "https://missionfocus.com"
  version "2.5.24"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/missionfocus/mfc/releases/download/v2.5.24/mfc_2.5.24_macOS_x86_64.tar.gz"
      sha256 "4d3242e3e901e4ed6cb7db2c48ea174ac925c1b3cae53b7e51950ec9d0b27755"
    end
    if Hardware::CPU.arm?
      url "https://github.com/missionfocus/mfc/releases/download/v2.5.24/mfc_2.5.24_macOS_arm64.tar.gz"
      sha256 "034c9f7d05ea26a958f41c00cf0acad2771355e4132a3ce62f2a1243a6a3492a"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/missionfocus/mfc/releases/download/v2.5.24/mfc_2.5.24_Linux_x86_64.tar.gz"
      sha256 "963e76f2b7a0a2cafd59eacb987cc5decb4d1ef6fde7fef9571a15c6667d1efd"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/missionfocus/mfc/releases/download/v2.5.24/mfc_2.5.24_Linux_arm64.tar.gz"
      sha256 "492473ad0f1e2a0fd68a78dfc9ce59fd262713ab6773758388c67a5a6bd24cba"
    end
  end

  def install
    bin.install "mfc"
  end

  test do
    system "#{bin}/mfc --version"
  end
end
